### ISSUE TITLE
Forward different port

### ISSUE THREAD

**Issue by GiovanniCardamone** [cinatic/kubectl-extension#7]
I noticed it's not possible to forward from one port to another when a tunnel it's created, would be nice to accept both sintax: `port` and `in_port:out_port` in case it's busy on host machine

**Comment by cinatic** [comment]
i am not sure if i understand the problem, you already can choose a local port by entering it in the window, the destination port is fixed by the service/pod you have choosen.

Like in this example you want to connect to the sql port, 3306 which is fixed and in the window you can choose your local part:
![sql](https://raw.githubusercontent.com/cinatic/kubectl-extension/main/images/services.png)

**Comment by GiovanniCardamone** [comment]
Sorry i missunderstood the usage, my bad.

I'll close this, thanks!
